on: [ push, pull_request ]
name: Build
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EtcTool-${{ matrix.os }}
          path: build
